export const TYPES = {
  Company: Symbol.for('Company'),
  Manager: Symbol.for('Manager'),
  Site: Symbol.for('Site'),
  Device: Symbol.for('Device'),
  HeartBeat: Symbol.for('HeartBeat'),
  NotificationService: Symbol.for('NotificationService'),
  AuthService: Symbol.for('AuthService'),
  CompanyService: Symbol.for('CompanyService'),
  RequireSignIn: Symbol.for('RequireSignIn'),
  Redis: Symbol.for('Redis'),
  SessionService: Symbol.for('SessionService'),
  ManagerService: Symbol.for('ManagerService'),
  HeartBeatService: Symbol.for('HeartBeatService'),
};
